apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: expense 
    module: backend
    environment: dev
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 #Service-Port
    targetPort: annotations-service #Target Port