apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: expense 
    module: backend
    environment: dev
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 #Service-Port
    targetPort: annot-svc #Target Port